= Sweet Reference Documentation
:toc: left
:nofooter:
:stylesdir: ./stylesheets
:source-highlighter: highlight.js
:highlightjs-theme: tomorrow

== Introduction

This is the reference document for Sweet.js. For a gentle explaination of Sweet's concepts see the link:tutorial.html[tutorial].

== Command Line API

- `--out-file <file>`: write result to file
- `--out-dir <dir>`: write result to directory
- `--no-babel`: do not use babel backend

== Binding Forms

=== `syntax`

----
syntax <name> = <init>
----

Bind `<name>` to the result of evaluating `<init>` in the compiletime environment. Scoping follows `let` (i.e. block scoped with a temporal dead zone).

If the result of evaluating `<init>` is a function, then the result is a <<syntax, _syntax transformer_>>.

=== `syntaxrec`

----
syntaxrec <name> = <init>
----

Identical to the `syntax` form except that `<name>` is also bound inside of `<init>`. This enables recursive macro definitions.

anchor:syntax[]

== Syntax Transformer

----
transformer : (TransformerContext) -> List(Syntax)
----

A syntax transformer is a function bound to a compile-time name. A syntax transformer is invoked with a <<context, *transformer context*>> that provides access to the syntax at the call-site and returns a list of <<synobj, syntax objects>>.



anchor:context[]

=== Transformer Context

A transformer context is an iterable object that provides access to syntax at the call-site of a syntax transformer.

----
TransformerContext = {
  next: (string?) -> {
    done: boolean,
    value: Syntax
  }
}
----

Each call to `next` returns the <<synobj, syntax object>> following the transformer call. If `next` is called with a string, the specified grammar production is matched.

anchor:synobj[]

== Syntax Objects

Syntax objects represent the syntax from the source program. Syntax objects have a number of methods to inspect their contents.

=== `.val()`

Returns a nullable value representing the textual value of the syntax. For example, the `.val()` of the identifier `foo` is the string `"foo"`. Some syntax objects (in particular delimiters) do not have a reasonable representation of their syntax and so `.val()` returns `null` in these cases.

=== `.lineNumber()`

Returns the original line number for this syntax object.

=== `.inner()`

If the syntax object is a delimiter, returns a <<context, transformer context>> iterator into the delimiter. Otherwise, throw an exception.

=== `.isIdentifier()`

Returns true if the syntax object is an identifier.

=== `.isBooleanLiteral()`
Returns true if the syntax object is a boolean literal.

=== `.isNullliteral()`
Returns true if the syntax object is a null literal.

=== `.isNumericLiteral()`
Returns true if the syntax object is a numeric literal.

=== `.isStringLiteral()`
Returns true if the syntax object is a string literal.

=== `.isKeyword()`
Returns true if the syntax object is a keyword.

=== `.isPunctuator()`
Returns true if the syntax object is a puncuator.

=== `.isRegularExpression()`
Returns true if the syntax object is a regular expression literal.

=== `.isTemplate()`
Returns true if the syntax object is a template literal.

=== `.isDelimiter()`
Returns true if the syntax object is a delimiter.

=== `.isParens()`
Returns true if the syntax object is a parenthesis delimiter (e.g. `( ... )`).

=== `.isBrackets()`
Returns true if the syntax object is a bracket delimiter (e.g. `[ ... ]`).

=== `.isBraces()`
Returns true if the syntax object is a braces delimiter (e.g. `{ ... }`).

=== `.isSyntaxTemplate()`

Returns true if the syntax object is a syntax template.


== Syntax Templates

Syntax templates construct a list of syntax objects from a literal representation using backtick (`\#`foo bar baz``). They are similar to ES2015 templates but with the special sweet.js specific `#` template tag.

Syntax templates support interpolations just like normal templates via `${...}`:

[source, javascript]
----
syntax m = function (ctx) {
  return #`${ctx.next().value} + 24`;
}
m 42
----

The expressions inside an interpolation must evaluate to a <<synobj, syntax object>>, an array, a list, or an <<context, transformer context>>.
