= Sweet Reference Documentation
:toc: left
:nofooter:
:stylesdir: ./stylesheets
:source-highlighter: highlight.js
:highlightjs-theme: tomorrow

== Introduction

This is the reference document for Sweet.js. For a gentle explaination of Sweet's concepts see the link:tutorial.html[tutorial].

== Command Line API

- `--out-file <file>`: write result to file
- `--out-dir <dir>`: write result to directory
- `--no-babel`: do not use babel backend

== Binding Forms

=== `syntax`

----
syntax <name> = <init>
----

Bind `<name>` to the result of evaluating `<init>` in the compiletime environment. Scoping follows `let` (i.e. block scoped with a temporal dead zone).

If the result of evaluating `<init>` is a function, then the result is a <<syntax, _syntax transformer_>>.

=== `syntaxrec`

----
syntaxrec <name> = <init>
----

Identical to the `syntax` form except that `<name>` is also bound inside of `<init>`. This enables recursive macro definitions.

anchor:syntax[]

== Syntax Transformer

----
transformer : (TransformerContext) -> List(Syntax)
----

A syntax transformer is a function bound to a compile-time name. A syntax transformer is invoked with a <<context, *transformer context*>> that provides access to the syntax at the call-site and returns a list of <<synobj, syntax objects>>.



anchor:context[]

=== Transformer Context

A transformer context is an iterable object that provides access to syntax at the call-site of a syntax transformer.

----
TransformerContext = {
  name: () -> Syntax
  next: () -> {
    done: boolean,
    value: Syntax
  }
  expand: (string) -> {
    done: boolean,
    value: Syntax
  }
  mark: () -> Marker
  reset: (Marker?) -> undefined
}
----

Each call to `next` returns the <<synobj, syntax object>> following the transformer call.

A call to `expand` initiates expansion at the current state of the iterator and matches the specified grammar production. Matching is "greedy" so `expand('expr')` with the syntax `1 + 2` matches the entire binary expression rather than just `1`. The following productions are accepted by `expand`:

- `Statement` with alias `stmt`
- `AssignmentExpression` with alias `expr`
- `Expression`
- `BlockStatement`
- `WhileStatement`
- `IfStatement`
- `ForStatement`
- `SwitchStatement`
- `BreakStatement`
- `ContinueStatement`
- `DebuggerStatement`
- `WithStatement`
- `TryStatement`
- `ThrowStatement`
- `ClassDeclaration`
- `FunctionDeclaration`
- `LabeledStatement`
- `VariableDeclarationStatement`
- `ReturnStatement`
- `ExpressionStatement`
- `YieldExpression`
- `ClassExpression`
- `ArrowExpression`
- `NewExpression`
- `ThisExpression`
- `FunctionExpression`
- `IdentifierExpression`
- `LiteralNumericExpression`
- `LiteralInfinityExpression`
- `LiteralStringExpression`
- `TemplateExpression`
- `LiteralBooleanExpression`
- `LiteralNullExpression`
- `LiteralRegExpExpression`
- `ObjectExpression`
- `ArrayExpression`
- `UnaryExpression`
- `UpdateExpression`
- `BinaryExpression`
- `StaticMemberExpression`
- `ComputedMemberExpression`
- `AssignmentExpression`
- `CompoundAssignmentExpression`
- `ConditionalExpression`

The `name()` method returns the syntax object of the macro name at the macro invocation site. This is usefulfootnote:[or will become useful as more features are implemented in Sweet] because it allows a macro transformer to get access to the lexical context at the invocation site.

A call to `mark` returns a pointer to the current state of the iterator.

Calling `reset` with no arguments returns the context to its initial state, while passing a Marker instance returns the context to the state pointed to by the marker.

[source, javascript]
----
syntax m = function (ctx) {
  ctx.expand('expr');
  ctx.reset();

  const a = ctx.next().value;
  ctx.next();

  const marker = ctx.mark();
  ctx.expand('expr');
  ctx.reset(marker);

  const b = ctx.next().value;
  return #`${a} + ${b} + 24`; // 30 + 42 + 24
}
m 30 + 42 + 66
----

anchor:synobj[]

== Syntax Objects

Syntax objects represent the syntax from the source program. Syntax objects have a number of methods to inspect their contents and construct new syntax object.


=== val


[source, javascript]
----
Syntax.prototype.val() -> string?
----

Returns a nullable value representing the textual value of the syntax object. For example, the `.val()` of the identifier `foo` is the string `"foo"`. Some syntax objects (in particular delimiters) do not have a reasonable representation of their syntax and so `.val()` returns `null` in these cases.

[source, javascript]
----
syntax m = ctx => {
  let id = ctx.next().value;
  let delim = ctx.next().value;

  id.val() === 'foo';   // true
  delim.val() === null; // true
  // ...
}
m foo (1)
----

=== lineNumber

[source, javascript]
----
Syntax.prototype.lineNumber() -> number
----

Returns the original line number for this syntax object.

=== inner

[source, javascript]
----
Syntax.prototype.inner() -> TransformerContext
----

If the syntax object is a delimiter, returns a <<context, transformer context>> iterator into the delimiter. Otherwise, throw an exception.

[source, javascript]
----
syntax m = ctx => {
  let delim = ctx.next().value;
  var arr = [];
  for (let item of delim.inner()) {
    arr.push(item);
  }
  return #`[${arr}]`;
}
m {
  1, 2, 3
}
----

=== from

[source, javascript]
----
Syntax.prototype.from(type, value) -> Syntax
  type : string
  value : any
----

Construct a new syntax object from the provided `type` and `value` using the instance syntax object's lexical context. Valid types are:

- `'null'`
- `'number'`
- `'string'`
- `'punctuator'`
- `'keyword'`
- `'identifier'`
- `'regularExpression'`
- `'braces'`
- `'brackets'`
- `'parens'`

[NOTE]
====
Be careful which syntax object you use to create a new syntax object via `from*` since the new object will share the original's lexical context. In most cases you will want to create a "dummy" syntax object inside a macro definition and then use that as a base to create new objects. For example,
[source, javascript]
----
syntax to_str = ctx => {
  let dummy = #`dummy`.get(0);
  let arg = ctx.next().value;
  return #`${dummy.fromString(arg.val())}`;
}
to_str foo
----
You may be tempted to reuse the syntax object provided by `ctx.name()` but resist that feeling! The `ctx.name()` syntax object comes from the macro call-site and so any syntax objects created from it will carry the lexical context of the call-site. Sometimes this is what you want, but most of the time this breaks hygiene!
====

=== fromNull

[source, javascript]
----
Syntax.prototype.fromNull() -> Syntax
----

Creates a null literal with the instance syntax object's lexical context.


[source, javascript]
----
syntax m = ctx => {
  let dummy = #`dummy`.get(0);
  return #`${dummy.fromNull()}`;
}
m
----

.(expansion)
----
null
----

=== fromNumber

[source, javascript]
----
Syntax.prototype.fromNumber(value) -> Syntax
  value : number
----

Creates a numeric literal matching `value` with the instance syntax object's lexical context.

[source, javascript]
----
syntax m = ctx => {
  let dummy = #`dummy`.get(0);
  return #`${dummy.fromNumber(1)}`;
}
m
----

.(expansion)
----
1
----

=== fromString

[source, javascript]
----
Syntax.prototype.fromString(value) -> Syntax
  value : string
----

Creates a string literal matching `value` with the instance syntax object's lexical context.

[source, javascript]
----
syntax to_str = ctx => {
  let dummy = #`dummy`.get(0);
  let arg = ctx.next().value;
  return #`${dummy.fromString(arg.val())}`;
}
to_str foo
----

.(expansion)
----
'foo'
----

=== fromPunctuator

[source, javascript]
----
Syntax.prototype.fromPunctuator(value) -> Syntax
  value : string
----

Creates a punctuator (e.g. `+`, `==`, etc.) matching `value` with the instance syntax object's lexical context.

[source, javascript]
----
syntax m = ctx => {
  let dummy = #`dummy`.get(0);
  return #`1 ${dummy.fromPunctuator('+')} 1`;
}
m
----

.(expansion)
----
1 + 1
----

=== fromKeyword

[source, javascript]
----
Syntax.prototype.fromKeyword(value) -> Syntax
  value : string
----

Creates a keyword matching `value` with the instance syntax object's lexical context.

[source, javascript]
----
syntax m = ctx => {
  let dummy = #`dummy`.get(0);
  return #`${dummy.fromKeyword('let')} x = 1`;
}
m
----

.(expansion)
----
let x = 1
----

=== fromIdentifier

[source, javascript]
----
Syntax.prototype.fromIdentifier(value) -> Syntax
  value : string
----

Creates a identifier matching `value` with the instance syntax object's lexical context.

[source, javascript]
----
syntax m = ctx => {
  let dummy = #`dummy`.get(0);
  let arg = ctx.next().value;
  return #`${dummy.fromIdentifier(arg.val())}`;
}
m foo
----

.(expansion)
----
foo
----


=== fromRegularExpression

[source, javascript]
----
Syntax.prototype.fromRegularExpression(value) -> Syntax
  value : string
----

Creates a regular expression literal matching `value` with the instance syntax object's lexical context.

[source, javascript]
----
syntax m = ctx => {
  let dummy = #`dummy`.get(0);
  return #`${dummy.fromRegularExpression('[a-zA-Z]*')}`;
}
m
----

.(expansion)
----
/[a-zA-Z]/
----

=== fromBraces

[source, javascript]
----
Syntax.prototype.fromBraces(inner) -> Syntax
  inner : List(Syntax)
----

Creates a curly brace delimiter with inner syntax objects `inner` with the instance syntax object's lexical context.

[source, javascript]
----
syntax m = ctx => {
  let dummy = #`dummy`.get(0);
  let block = #`let x = 1;`;
  return #`${dummy.fromBraces(block)}`;
}
m
----

.(expansion)
----
{
  let x = 1;
}
----

=== fromBrackets

[source, javascript]
----
Syntax.prototype.fromBrackets(inner) -> Syntax
  inner : List(Syntax)
----

Creates a square bracket delimiter with inner syntax objects `inner` with the instance syntax object's lexical context.

[source, javascript]
----
syntax m = ctx => {
  let dummy = #`dummy`.get(0);
  let elements = #`1, 2, 3`;
  return #`${dummy.fromBrackets(elements)}`;
}
m
----

.(expansion)
----
[1, 2, 3]
----

=== fromParens

[source, javascript]
----
Syntax.prototype.fromParens(inner) -> Syntax
  inner : List(Syntax)
----

Creates a parenthesis delimiter with inner syntax objects `inner` with the instance syntax object's lexical context.

[source, javascript]
----
syntax m = ctx => {
  let dummy = #`dummy`.get(0);
  let expr = #`5 * 5`;
  return #`1 + ${dummy.fromParens(expr)}`;
}
m
----

.(expansion)
----
1 + (5 * 5)
----

=== isIdentifier

[source, javascript]
----
Syntax.prototype.isIdentifier() -> boolean
----

Returns true if the syntax object is an identifier.

=== isBooleanLiteral

[source, javascript]
----
Syntax.prototype.isBooleanLiteral() -> boolean
----

Returns true if the syntax object is a boolean literal.

=== isNullLiteral

[source, javascript]
----
Syntax.prototype.isNullLiteral() -> boolean
----

Returns true if the syntax object is a null literal.

=== isNumericLiteral

[source, javascript]
----
Syntax.prototype.isNumericLiteral() -> boolean
----

Returns true if the syntax object is a numeric literal.

=== isStringLiteral

[source, javascript]
----
Syntax.prototype.isStringLiteral() -> boolean
----

Returns true if the syntax object is a string literal.

=== isKeyword

[source, javascript]
----
Syntax.prototype.isKeyword() -> boolean
----

Returns true if the syntax object is a keyword.

=== isPunctuator

[source, javascript]
----
Syntax.prototype.isPunctuator() -> boolean
----

Returns true if the syntax object is a puncuator.

=== isRegularExpression

[source, javascript]
----
Syntax.prototype.isRegularExpression() -> boolean
----

Returns true if the syntax object is a regular expression literal.

=== isTemplate

[source, javascript]
----
Syntax.prototype.isTemplate() -> boolean
----

Returns true if the syntax object is a template literal.

=== isDelimiter

[source, javascript]
----
Syntax.prototype.isDelimiter() -> boolean
----

Returns true if the syntax object is a delimiter.

=== isParens

[source, javascript]
----
Syntax.prototype.isParens() -> boolean
----

Returns true if the syntax object is a parenthesis delimiter (e.g. `( ... )`).

=== isBrackets

[source, javascript]
----
Syntax.prototype.isBrackets() -> boolean
----

Returns true if the syntax object is a bracket delimiter (e.g. `[ ... ]`).

=== isBraces

[source, javascript]
----
Syntax.prototype.isBraces() -> boolean
----

Returns true if the syntax object is a braces delimiter (e.g. `{ ... }`).

=== isSyntaxTemplate

[source, javascript]
----
Syntax.prototype.isSyntaxTemplate() -> boolean
----

Returns true if the syntax object is a syntax template.


== Syntax Templates

Syntax templates construct a list of syntax objects from a literal representation using backtick (`\#`foo bar baz``). They are similar to ES2015 templates but with the special sweet.js specific `#` template tag.

Syntax templates support interpolations just like normal templates via `${...}`:

[source, javascript]
----
syntax m = function (ctx) {
  return #`${ctx.next().value} + 24`;
}
m 42
----

The expressions inside an interpolation must evaluate to a <<synobj, syntax object>>, an array, a list, or an <<context, transformer context>>.
