= Sweet Tutorial
:toc: left
:nofooter:
:stylesdir: ./stylesheets
:source-highlighter: highlight.js
:highlightjs-theme: tomorrow
:icons: font

== Introduction

Sweet brings the hygienic macros of languages like Scheme and Rust to JavaScript.
Macros allow you to sweeten the syntax of JavaScript and craft the language you’ve always wanted.

NOTE: This documents version 1.0 of Sweet and is currently a work in progress. Contributions are welcome!

== Installation and Getting Started

Install Sweet with npm:

[source, sh]
----
$ npm install sweet.js
----

This installs the `sjs` binary into your `node_modules` folder.

TIP: You can also install `sjs` globally with the `-g` flag if you'd like.

For example, say you'd like to sweeten JavaScript with a simple hello world macro.
You can write it down as the following:

.sweet_code.js
[source, javascript]
----
syntax hi = function (ctx) {
  return #`console.log('hello, world!')`;
}
hi
----

Then, you can use the `sjs` command to compile the sweetened code into plain JavaScript:

[source, sh]
----
$ node_modules/.bin/sjs sweet_code.js
console.log('hello, world!')
----

== Sweet Hello

So how do macros work?
Well, in a sense macros are a bit like compiletime functions; just like functions, macros have definitions and invocations which work together to abstract code into a single location so you don't keep repeating yourself.

Consider the hello world example again:

[source,javascript]
----
syntax hi = function (ctx) { // <1>
  return #`console.log('hello, world!')`; // <2>
}
hi // <3>
----
<1> Macro definition
<2> Syntax Template
<3> Macro invocation

The first three lines make up the macro definition. The `syntax` keyword is a bit like `var` or `let` in that it creates a new variable. However, rather than create a variable for a runtime value, `syntax` creates a new variable for a _compiletime value_. In this case, `hi` is the variable bound to the compiletime function defined on the first three lines.

NOTE: In this example, `syntax` sets the variable to a function, but the variable can be set to any JavaScript value. Currently, this point is rather academic since Sweet does not provide a way to actually _use_ anything other than a compiletime function. However, this feature will be added eventually.

Once a macro has been defined, it can be invoked. On line three above the macro is invoked simply by writing `hi`.

When the Sweet compiler sees the `hi` identifier bound to the compiletime function, the function is invoked and its return value is used to replace the invoking occurrence of `hi`. In this case, that means that `hi` is replaced with `console.log('hello, world!')`.

Compiletime functions defined by `syntax` must return an array of syntax objects. You can easily create these with a _syntax template_. Syntax templates are template literals with a `\#` tag, which create an arrayfootnote:[Technically, syntax templates return an link:https://facebook.github.io/immutable-js/docs/#/List[immutable.js List] but Sweet converts between arrays and Lists for you]
of syntax objects.

Syntax Object::
Sweet's internal representation of syntax. Syntax objects are somewhat like tokens from traditional compilers except that delimiters cause syntax objects to nest. This nesting gives Sweet more structure to work with during compilation. If you are coming from Lisp or Scheme, you can think of them a bit like s-expressions.


== Sweet New

Let's move on to a slightly more interesting example.
Pretend you are using an OO framwork for JavaScript where instead of using `new` we want to call a `.create` method that has been monkey patched onto `Function.prototype` (don't worry, I won't judge...much). Rather than manually rewrite all usages of `new` to the `create` method you could define a macro that does it for you.

.New Macro
[source, javascript]
----
syntax new = function (ctx) {
  let ident = ctx.next().value;
  let params = ctx.next().value;
  return #`${ident}.create ${params}`;
}

new Droid('BB-8', 'orange');
----

.(Expansion)
[source, javascript]
----
Droid.create('BB-8', 'orange');
----

Here you can see the `ctx` parameter to the macro provides access to syntax at the macro call-site. This parameter is an iterator called the _macro context_.

Macro Context::
An iterator over the syntax where the macro was called. It has the type:
+
----
{
  next: (string?) -> {
    done: boolean,
    value: Syntax
  }
}
----
+
Each call to `next` returns the successive syntax object in `value` until there is nothing left in which case `done` is set to true. Note that the context is also an iterable so you can use `for-of` and related goodies.

Note that in this example we only call `next` twice even though it looks like there is more than two bits of syntax we want to match. What gives? Well, remember that delimiters cause syntax objects to nest. So, as far as the macro context is concerned there are two syntax objects: `Droid` and a single paren delimiter syntax object containing the three syntax objects `'BB-8'`, `,`, and `'orange'`.

After grabbing both syntax objects with the macro context iterator we can stuff them into a syntax template. Syntax templates allow syntax objects to be used in interpolations so it is straightforward to get our desired result.

== Sweet Let

Ok, time to make some ES2015. Let's say we want to implement `let`.footnote:[Note that we don't have to do this since Sweet already parses `let` statements just fine and uses babel as a backend to provide support in non-ES2015 environments.]
We only need one new feature you haven't seen yet:


.Let Macro
[source, javascript]
----
syntax let = function (ctx) {
  let ident = ctx.next().value;
  // eat `=`
  ctx.next();
  let init = ctx.next('expr').value; // <1>
  return #`
    (function (${ident}) {
      ${ctx} // <2>
    }(${init}))
  `
}

let bb8 = new Droid('BB-8', 'orange');
console.log(bb8.beep());
----
<1> Match an expression
<2> A macro context in the template will consume the iterator

.(Expansion)
[source, javascript]
----
(function(bb8) {
  console.log(bb8.beep());
})(Droid.create("BB-8", "orange"));
----

Calling `next` with a string argument allows us to specify the grammar production we want to match; in this case we are matching an expression. You can think matching against a grammar production a little like matching an implicitly-delimited syntax object; these matches group multiple syntax object together.
